// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/hero-variants/VariantA.tsx": () => import("../components/mockups/hero-variants/VariantA.tsx"),
  "./components/mockups/hero-variants/VariantB.tsx": () => import("../components/mockups/hero-variants/VariantB.tsx"),
  "./components/mockups/property-card/EditorialLight.tsx": () => import("../components/mockups/property-card/EditorialLight.tsx"),
  "./components/mockups/property-card/LuxuryDark.tsx": () => import("../components/mockups/property-card/LuxuryDark.tsx")
};
